# from https://github.com/k3d-io/k3d-demo/blob/main/assets/k3d-config-registry.yaml
apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: hash
servers: 1
agents: 1
ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 443:443
    nodeFilters:
      - loadbalancer
registries:
  create:
    name: hash-registry.localhost
    hostPort: "5000"

options:
  k3d:
    wait: true
    timeout: "360s"
  k3s:
    extraArgs:
      # We want to use nginx, so disable traefik
      - arg: --disable=traefik
        nodeFilters:
          - server:*
