{{- $component := dict
  "ctx" .
  "component" "frontend"
  "domain" .Values.frontend.domain
-}}
{{- $port := .Values.frontend.port -}}
{{- $image := .Values.frontend.image -}}
{{- $fullName := include "component.fullname" $component -}}
{{- $configMapName := printf "%s-config" $fullName -}}
{{- $apiServiceDns := include "serviceHost" (dict "ctx" . "component" "api") -}}
{{- $kratosServiceDns := include "serviceHost" (dict "ctx" . "component" "kratos") -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configMapName }}
  labels:
    {{- include "component.labels" $component | nindent 4 }}

data:
  FRONTEND_URL: {{ print "http://" .Values.frontend.domain | quote }}
  API_ORIGN: {{ print "http://" .Values.api.domain | quote }}

  SYSTEM_USER_SHORTNAME:  {{ .Values.api.SYSTEM_USER_SHORTNAME | quote }}
  SYSTEM_USER_PREFERRED_NAME:  {{ .Values.api.SYSTEM_USER_PREFERRED_NAME | quote }}

  ORY_KRATOS_PUBLIC_URL: {{ include "serviceUrl" (dict "serviceDns" $kratosServiceDns "port" .Values.kratos.publicPort ) | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName | quote }}
  labels:
    {{- include "component.labels" $component | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ $port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "component.selectorLabels" $component | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "component.labels" $component | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "component.selectorLabels" $component | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "component.labels" $component | nindent 8 }}
    spec:
      initContainers:
        - name: init-redis-dependency
          image: busybox:1.35
          command: ["sh", "-c", "until nslookup {{ $apiServiceDns }}.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for redis; sleep 2; done"]
      containers:
        - name: {{ include "component" $component }}
          image: {{ $image | quote }}
          # Or `Never` if we want to only use pre-built images...
          # See https://kubernetes.io/docs/concepts/containers/images/#pre-pulled-images
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: {{ $configMapName }}
          ports:
            - name: http
              containerPort: {{ $port }}
              protocol: TCP
          livenessProbe:
            {{- include "probe-threshold-nodejs" . | nindent 12 }}
            httpGet:
              path: /api/ory/health/alive
              port: http
          readinessProbe:
            {{- include "probe-threshold-nodejs" . | nindent 12 }}
            httpGet:
              path: /api/ory/health/ready
              port: http
