{{- $app := .Release.Name -}}
{{- $component := dict
  "ctx" .
  "component" "ingress"
-}}
{{- $fullName := include "component.fullname" $component -}}
{{- $kratos := dict
  "ctx" .
  "component" "kratos"
  "domain" .Values.kratos.domain
-}}
{{- $api := dict
  "ctx" .
  "component" "api"
  "domain" .Values.api.domain
-}}
{{- $frontend := dict
  "ctx" .
  "component" "frontend"
  "domain" .Values.frontend.domain
-}}
{{- $k8sdash := dict
  "ctx" .
  "domain" (printf "%s.%s" .Values.dev.k8sdash.subdomain .Values.dev.domain)
-}}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    
  labels:
    {{- include "component.labels" $component | nindent 4 }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ include "component.domain" $frontend | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "component.fullname" $frontend }}
                port:
                  number: {{ .Values.frontend.port }}
    - host: {{ include "component.domain" $kratos | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "component.fullname" $kratos }}
                port:
                  number: {{ .Values.kratos.publicPort }}
    - host: {{ include "component.domain" $api | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "component.fullname" $api }}
                port:
                  number: {{ .Values.api.internal.port }}
    {{- if .Values.dev.k8sdash.enable }}
    - host: {{ include "component.domain" $k8sdash | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hash-kubernetes-dashboard
                port:
                  number: 8080
    {{- end }}
